# Generated by Django 5.2.5 on 2025-08-16 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/%Y/%m/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('full_name', models.CharField(editable=False, max_length=120, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('slug', models.SlugField(blank=True, help_text='Identificador público (ej. jvasquez)', unique=True, verbose_name='Slug')),
                ('cohort', models.CharField(blank=True, max_length=80, verbose_name='Promocion/Seccion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(blank=True, help_text="Obsoleto: usar 'Curso' arriba.", max_length=160, verbose_name='Tipo de certificacion')),
                ('credly_url', models.URLField(blank=True, verbose_name='URL de Credly')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Fecha de emision')),
                ('badge_image', models.ImageField(blank=True, upload_to='badges/', verbose_name='Insignia (archivo)')),
                ('badge_image_url', models.URLField(blank=True, verbose_name='Imagen de insignia (URL opcional)')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones', to='registry.curso', verbose_name='Curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='registry.student')),
            ],
            options={
                'verbose_name': 'Certificacion',
                'verbose_name_plural': 'Certificaciones',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
